spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_db?useSSL=false&serverTimezone=UTC
    username: seyha
    password: $Eyha@123;

  jpa:
    hibernate:
      ddl-auto: validate   # important later
    show-sql: true
    properties:
      hibernate:
        format_sql: true